name: sunmachine
description: Smart lighting system
version: 0.7.3+4

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  app_settings: 4.1.8
  device_info_plus: ^8.0.0
  flutter_native_timezone: ^2.0.0
  flutter_reactive_ble: ^5.0.3
  permission_handler: ^10.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.11.0
  flutter_lints: ^2.0.1
  flutter_native_splash: ^2.2.16

flutter:
  uses-material-design: true
  assets:
    - intro.png
    - intro-dark.png
    - intro-opa.png
    - tzdata.json

flutter_icons:
  image_path: 'assets/appicon.png'
  android: true
  adaptive_icon_background: '#bed6fe'
  adaptive_icon_foreground: 'assets/appicon-adpt.png'
  ios: true
  remove_alpha_ios: true

flutter_native_splash:
  color: '#bed6fe'
  color_dark: '#393b3f'
  image: 'assets/appicon-spl.png'
  android_12:
    color: '#bed6fe'
    color_dark: '#393b3f'
    image: 'assets/appicon-spl.png'
