name: sunmachine
description: Smart lighting system
version: 0.7.6+7

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  app_settings: ^5.1.1
  device_info_plus: ^9.1.0
  flutter_blue_plus: ^1.30.5
  flutter_timezone: ^1.0.8
  permission_handler: ^11.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.1
  flutter_native_splash: ^2.3.2

flutter:
  uses-material-design: true
  assets:
    - assets/intro.png
    - assets/intro-dark.png
    - assets/intro-opa.png
    - assets/tzdata.json

flutter_icons:
  image_path: 'assets/appicon.png'
  android: true
  adaptive_icon_background: '#bed6fe'
  adaptive_icon_foreground: 'assets/appicon-adpt.png'
  ios: true
  remove_alpha_ios: true

flutter_native_splash:
  color: '#bed6fe'
  color_dark: '#393b3f'
  image: 'assets/appicon-spl.png'
  android_12:
    color: '#bed6fe'
    color_dark: '#393b3f'
    image: 'assets/appicon-spl.png'
