name: sunmachine
description: Smart lighting system
version: 0.7.3+4

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  device_info_plus: ^8.0.0
  flutter_native_timezone: ^2.0.0
  flutter_reactive_ble: ^5.0.2
  location: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.10.0
  flutter_lints: ^2.0.1
  flutter_native_splash: ^2.2.13

flutter:
  uses-material-design: true
  assets:
    - intro.png
    - intro-dark.png
    - intro-opa.png
    - tzdata.json

flutter_icons:
  android: false
  ios: true
  image_path: 'assets/appicon.png'

flutter_native_splash:
  color: '#fefbff'
  color_dark: '#1b1b1f'
  image: 'assets/intro.png'
  image_dark: 'assets/intro-dark.png'
