name: sunmachine
description: Sunmachine
publish_to: 'none'
version: 0.6.1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.3
  device_info_plus: ^2.1.0
  flutter_native_timezone: ^2.0.0
  flutter_reactive_ble: ^4.0.0
  location: ^4.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2

flutter:
  uses-material-design: true
  assets:
    - intro.png
    - intro-opa.png
    - tzdata.json

flutter_icons:
  android: false
  ios: true
  image_path: 'assets/appicon.png'
